variable "OCID_TENANCY" {}
variable "OCID_USER" {}
variable "OCID_FINGERPRINT" {}
#variable "OCID_PRIVATE_KEY" {}
variable "OCID_PRIVATE_KEY_PATH" {}
variable "OCID_COMPARTMENT" {}
variable "OCID_SUBNET" {}
variable "OCID_SOURCE" {}
variable "OCID_VCN" {}
