bootstrap = <<SCRIPT
  useradd -m ubuntu --groups sudo -p vagrant -s /bin/bash
  echo -e "vagrant\nvagrant\n" | passwd ubuntu
  cp -r /home/vagrant/.ssh /home/ubuntu/
  chown ubuntu:ubuntu /home/ubuntu/.ssh
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provision "shell", inline: "#{bootstrap}", privileged: true
  #config.ssh.username = "ubuntu"
end
