name: terraform

on:
  pull_request:
    paths:
      - '.github/workflows/terraform.yml'
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get terraform version
        id: terraform_version
        working-directory: terraform
        run: |
          echo -n "::set-output name=version::"
          cat .terraform-version

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.version }}

      - name: check format
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: tflint with reviewdog
        uses: reviewdog/action-tflint@v1.18.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: init
        working-directory: terraform
        run: terraform init -backend=false

      - name: validate
        working-directory: terraform
        run: terraform validate
        env:
          GITHUB_APP_ID: 123456
          GITHUB_APP_INSTALLATION_ID: 12345678
          GITHUB_APP_PEM_FILE: "\n"
