name: terraform plan

on:
  pull_request:
    paths:
      - '.github/workflows/terraform-plan.yml'
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.11
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: init
        working-directory: terraform
        run: terraform init

      - name: plan
        working-directory: terraform
        run: terraform plan
